name: weather
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.1
  http: ^0.13.5
  animated_text_kit: ^4.2.2
  animations: ^2.0.3
  weather_icons: ^3.0.0
  intl: ^0.17.0
  rflutter_alert: ^2.0.4
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon_luncher"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - images/Search.jpg
    - images/Thunderstorm-Day.jpg
    - images/Thunderstorm-Night.jpg
    - images/Rainy_Day.jpg
    - images/Rainy_Night.jpg
    - images/Snow_Day.jpg
    - images/Snow_Night.jpg
    - images/Mist.jpg
    - images/Clear_Day.jpg
    - images/Clear_Night.jpg
    - images/few_clouds_Day.jpg
    - images/few_clouds_Night.jpg
    - images/broken_clouds_Day.jpg
    - images/broken_clouds_Night.jpg
    - images/Clouds_Day.jpg
    - images/Clouds_Night.jpg
    - images/tornado.jpg

  fonts:
    - family: Caveat-Regular
      fonts:
        - asset: fonts/Caveat-Regular.ttf
    - family: Kalam-Regular
      fonts:
        - asset: fonts/Kalam-Regular.ttf




